services:
  app:
    build: .
    container_name: backend_ta_lautan_teduh
    restart: always
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=ta-lautan
      - DB_NAME=ta_lautan_db

  db:
    image: postgres:15
    container_name: database_ta_lautan_teduh
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ta-lautan
      POSTGRES_DB: ta_lautan_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_ta_lautan
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
