server {
    listen 80;
    server_name rakaascode.site www.rakaascode.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name rakaascode.site www.rakaascode.site;

    ssl_certificate /etc/letsencrypt/live/rakaascode.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rakaascode.site/privkey.pem;

    location / {
        proxy_pass http://backend_ta_lautan_teduh:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
